import { int, sqliteTable, text } from "drizzle-orm/sqlite-core";
export const usersTable = sqliteTable("users_table", {
  id: int().primaryKey({ autoIncrement: true }),
  name: text().notNull(),
  age: int().notNull(),
  email: text().notNull().unique(),
});

// Table for user-added songs (matches AddSongScreen fields)
export const userSongsTable = sqliteTable("user_songs", {
  // `id` is a string generated by `makeUserSongId()`
  id: text().primaryKey(),
  title: text().notNull(),
  artist: text().notNull(),
  // musical key, e.g., "C" or "Gm"
  key: text(),
  // capo position (integer), optional
  capo: int(),
  // beats per minute, optional
  bpm: int(),
  // comma-separated tags, e.g., "worship,easy,nepali"
  tags: text().notNull(),
  // song lines stored as newline-separated text
  lines: text().notNull(),
});
